### ISSUE TITLE
Cannot find module 'styled-components'

### ISSUE THREAD

**Issue by sultanaslam** [saisandeepvaddi/styled-loaders-react#3]
1.0.0 was working fine but when i updated it to 1.0.1 this error occur

**Comment by saisandeepvaddi** [comment]
`styled-components` is moved to peerDependencies in 1.0.1 along with react, react-dom, prop-types. So user is expected to install `styled-components` separately in their project.

Can you try installing styled-components in your project.

**Comment by sultanaslam** [comment]
solved. but it should be pre install in styled-loaders-react package.

**Comment by saisandeepvaddi** [comment]
Nice that it's working now. If it is pre-installed, then the user might get conflicts in styled-components versions if they already have styled-components installed and will cause problems. Please see https://github.com/saisandeepvaddi/styled-loaders-react/pull/1

**Comment by sultanaslam** [comment]
Then it should be mention in docs. Thanks for your time
